server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
